[package]
name = "cucumber"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tester"
path = "./src/tester.rs"

[dependencies]
anyhow = "1.0.72"
indicatif = "0.17.6"
krakatau2 = { path = "../Krakatau" }
md5 = "0.7.0"
rand = "0.8.5"
xml-rs = "0.8.16"
