//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "auth_provider")]
pub enum AuthProvider {
    #[sea_orm(string_value = "discord")]
    Discord,
    #[sea_orm(string_value = "facebook")]
    Facebook,
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "google")]
    Google,
    #[sea_orm(string_value = "kicrosoft")]
    Kicrosoft,
    #[sea_orm(string_value = "spotify")]
    Spotify,
    #[sea_orm(string_value = "twitter")]
    Twitter,
}
