//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub display_name: String,
    pub show_display_name: bool,
    pub bio: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::external_user::Entity")]
    ExternalUser,
}

impl Related<super::external_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExternalUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
